"""Report formatter: exports VLABlueprint to Markdown and JSON formats."""

import json
from typing import Dict, List
from vla_engine.models.blueprint import VLABlueprint
from vla_engine.models.resource import Category


class ReportFormatter:
    """Formats VLABlueprint into professional Markdown dossiers and JSON exports."""

    @staticmethod
    def to_markdown(blueprint: VLABlueprint) -> str:
        """Generate a publication-grade GitHub-flavored markdown report."""
        lines = []

        # Title
        lines.append("# Vision-Language-Action (VLA) Model Development Blueprint")
        lines.append("")
        lines.append(f"> **Generated by:** Intelligent VLA Resource Discovery & Ranking Engine  ")
        lines.append(f"> **Timestamp:** {blueprint.generated_at}  ")
        lines.append(f"> **Query:** *\"{blueprint.query.raw_query}\"*  ")
        lines.append("")

        # Query Breakdown Callout
        lines.append("## 1. Query Analysis & Intent Decomposition")
        lines.append("")
        lines.append("| Dimension | Extracted Values |")
        lines.append("| :--- | :--- |")
        lines.append(f"| **Target Tasks** | {', '.join(blueprint.query.target_tasks) or 'General Manipulation'} |")
        lines.append(f"| **Modalities** | {', '.join(blueprint.query.modalities)} |")
        lines.append(f"| **Target Embodiments** | {', '.join(blueprint.query.target_embodiments) or 'General Multi-Embodiment (Franka, WidowX, ALOHA)'} |")
        lines.append(f"| **Evaluated Pillars** | {len(blueprint.all_ranked_resources)} Pillars ({', '.join(c.display_name for c in blueprint.all_ranked_resources.keys())}) |")
        lines.append("")

        # Executive Stack Recommendation
        lines.append("## 2. Recommended Optimal VLA Technical Stack")
        lines.append("")
        lines.append(f"**Overall Ecosystem Compatibility Score:** `{blueprint.compatibility_score} / 100`  ")
        lines.append(f"**Coherence Verdict:** {blueprint.compatibility_verdict}  ")
        lines.append("")
        lines.append("| Pillar | Recommended Resource | Organization / Authors | License | Composite Score | Primary Links |")
        lines.append("| :--- | :--- | :--- | :--- | :---: | :--- |")

        pillar_order = [
            Category.VLM_BACKBONE,
            Category.VLA_POLICY,
            Category.ROBOTICS_DATASET,
            Category.SIMULATION,
            Category.TRAINING_FRAMEWORK,
        ]

        for cat in pillar_order:
            res = blueprint.top_stack.get(cat)
            if res:
                links = []
                if res.github_url:
                    links.append(f"[GitHub]({res.github_url})")
                if res.hf_url:
                    links.append(f"[HF Hub]({res.hf_url})")
                if res.paper_url:
                    links.append(f"[Paper]({res.paper_url})")
                link_str = " \\| ".join(links) if links else "[Link](" + (res.url or "#") + ")"
                score_str = f"**{res.final_score:.1f}**"
                org_str = res.organization or (res.authors[:30] + "..." if res.authors else "Open Source")
                lines.append(f"| **{cat.display_name}** | **{res.name}** | {org_str} | `{res.license}` | {score_str} | {link_str} |")

        lines.append("")

        # Step-by-Step Training Blueprint
        lines.append("## 3. End-to-End Implementation & Training Roadmap")
        lines.append("")
        for step in blueprint.pipeline_steps:
            lines.append(f"### Step {step.step_number}: {step.title}")
            lines.append(f"{step.description}")
            lines.append("")
            lines.append(f"- **Key Components:** {', '.join(step.recommended_tools)}")
            lines.append(f"- **Inputs:** {step.inputs}")
            lines.append(f"- **Outputs:** {step.outputs}")
            lines.append(f"- **Hardware Allocation:** {step.hardware_notes}")
            lines.append("")

        # Hardware Infrastructure Summary
        lines.append("## 4. Hardware Infrastructure Specifications")
        lines.append("")
        lines.append("| Infrastructure Tier | Recommended Hardware & Sizing |")
        lines.append("| :--- | :--- |")
        for k, v in blueprint.hardware_summary.items():
            lines.append(f"| **{k}** | {v} |")
        lines.append("")

        # Category Deep-Dives & Leaderboards
        lines.append("## 5. Detailed Category Leaderboards & Multi-Factor Scoring")
        lines.append("")
        lines.append("Each candidate was scored across 5 dimensions: **Relevance** (35%), **Adoption** (20%), **Reproducibility** (20%), **Freshness** (15%), and **Compatibility** (10%).")
        lines.append("")

        for cat in pillar_order:
            res_list = blueprint.all_ranked_resources.get(cat, [])
            if not res_list:
                continue

            lines.append(f"### {cat.display_name}")
            lines.append("")
            lines.append("| Rank | Name | Score | Rel (35%) | Adopt (20%) | Repro (20%) | Fresh (15%) | Compat (10%) | Stars / Downloads |")
            lines.append("| :---: | :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |")

            for rank, r in enumerate(res_list, 1):
                sc = r.scores
                stars_dl = f"★ {r.github_stars:,} / ⬇ {r.hf_downloads:,}"
                if sc:
                    lines.append(
                        f"| {rank} | **{r.name}** | **{sc.composite_score:.1f}** | "
                        f"{sc.semantic_relevance:.1f} | {sc.community_adoption:.1f} | "
                        f"{sc.reproducibility:.1f} | {sc.freshness:.1f} | {sc.compatibility:.1f} | "
                        f"{stars_dl} |"
                    )
                else:
                    lines.append(f"| {rank} | **{r.name}** | {r.final_score:.1f} | - | - | - | - | - | {stars_dl} |")

            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def to_json(blueprint: VLABlueprint, indent: int = 2) -> str:
        """Export blueprint and rankings to JSON format."""
        return json.dumps(blueprint.model_dump(), indent=indent)
